# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/posterous.rb'

Hoe.new('posterous', Posterous::VERSION) do |p|
  p.developer('Jordan Dobson', 'jordan.dobson@madebysquad.com')
  p.extra_deps = ['httparty', 'mocha']
end

# vim: syntax=Ruby
